# https://alacritty.org/config-alacritty.html
# https://github.com/alacritty/alacritty-theme

live_config_reload = true
import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]


[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 187, lines = 63 }
position = { x = 1268, y = 475 }
decorations = "None"                       # "Full" | "None" | "Transparent" | "Buttonless"
decorations_theme_variant = "None"
dynamic_title = true
resize_increments = true
opacity = 0.80
blur = true
# title = ""
padding = { x = 0, y = 0 }
dynamic_padding = true
startup_mode = "Windowed"  # "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"


[font]
size = 12
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
builtin_box_drawing = true
offset = { x = 0, y = 1 }
glyph_offset = { x = 0, y = 0 }

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
thickness = 0.32
unfocused_hollow = true
style = { shape = 'Beam', blinking = "Always" }

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "l", mods = "Command", command = { program = "sh", args = [
    "-lc",
    "ALACRITTY_CWD=$(pwd) alacritty -e zsh -c 'cd $ALACRITTY_CWD && lazygit'",
  ] } },
]
