[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xffa066"
index = 16

[[colors.indexed_colors]]
color = "0xff5d62"
index = 17

[colors.bright]
black = "0x727169"
blue = "0x7fb4ca"
cyan = "0x7aa89f"
green = "0x98bb6c"
magenta = "0x938aa9"
red = "0xe82424"
white = "0xdcd7ba"
yellow = "0xe6c384"

[colors.normal]
black = "0x090618"
blue = "0x7e9cd8"
cyan = "0x6a9589"
green = "0x76946a"
magenta = "0x957fb8"
red = "0xc34043"
white = "0xc8c093"
yellow = "0xc0a36e"

[colors.primary]
background = "0x1f1f28"
foreground = "0xdcd7ba"

[colors.selection]
background = "0x2d4f67"
foreground = "0xc8c093"

[cursor]
thickness = 0.3
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "alacritty"

[font]
builtin_box_drawing = true
size = 14.0

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[window]
decorations = "buttonless"
decorations_theme_variant = "None"
dynamic_padding = true
dynamic_title = true
opacity = 0.9
title = ""

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0
