
[colors]
background = "#0F111A"
foreground = "#A6ACCD"
selection-background = "#444267"
selection-foreground = "#A6ACCD"
tabs-active = "#6E98EB"
cursor = "#E6B455"
vi-cursor = "#E6B455"
# Regular colors
black = "#000000"
blue = "#82AAFF"
cyan = "#89DDFF"
green = "#C3E88D"
magenta = "#C792EA"
red = "#F07178"
tabs = "#0F111A"
white = "#EEFFFF"
yellow = "#FFCB6B"
# # Dim colors
dim-black = "#090B10"
dim-blue = "#6E98EB"
dim-cyan = "#71C6E7"
dim-foreground = "#717CB4"
dim-green = "#ABCF76"
dim-magenta = "#B480D6"
dim-red = "#DC6068"
# dim-white = "None"
dim-yellow = "#E6B455"
# Light colors
light-black = "#090B10"
light-blue = "#6E98EB"
light-cyan = "#71C6E7"
light-foreground = "#717CB4"
light-green = "#ABCF76"
light-magenta = "#B480D6"
light-red = "#DC6068"
