customCommands:
  - key: "<c-r>"
    command: 'hub browse -- "commit/{{.SelectedLocalCommit.Sha}}"'
    context: "commits"
  - key: "a"
    command: "git {{if .SelectedFile.HasUnstagedChanges}} add {{else}} reset {{end}} {{.SelectedFile.Name | quote}}"
    context: "files"
    description: "toggle file staged"
  - key: "C"
    command: "git commit"
    context: "global"
    subprocess: true
  - key: "r"
    command: "git submodule update --remote"
    context: "submodules"
    description: "update remote submodule"
  - key: "<c-f>"
    command: "git fetch --prune origin"
    context: "localBranches"
    loadingText: "Pruning..."
    description: "fetch prune origin"
  - key: "N"
    description: "Create local wip branch"
    command: "git branch {{if index .PromptResponses 0}}{{index .PromptResponses 0}}/{{end}}{{index .PromptResponses 1}}"
    context: "localBranches"
    loadingText: "Creating branch..."
    prompts:
      - type: "menu"
        title: "What kind of branch is it?"
        options:
          - name: "feature"
            description: "   a feature branch"
            value: "feature"
          - name: "hotfix"
            description: "   a hotfix branch"
            value: "hotfix"
          - name: "release"
            description: "   a release branch"
            value: "release"
          - name: "skip"
            description: "   a skip branch kind"
            value: ""
      - type: "input"
        title: "What is the description of branch?"
        initialValue: ""
  - key: "D"
    description: "Remove a branch description"
    command: "git config --unset branch.{{.SelectedLocalBranch.Name}}.description"
    context: "localBranches"
    loadingText: "Removing description..."
    prompts:
      - type: "confirm"
        title: "Confirm:"
        body: "Are you sure you want to remove description?"
  - key: "e"
    description: "Add/edit a branch description"
    command: "git branch --edit-description"
    context: "localBranches"
    loadingText: "Opening editor..."
    subprocess: true
  - key: "s"
    description: "show branch description"
    command: "git config branch.{{.SelectedLocalBranch.Name}}.description"
    context: "localBranches"
    showOutput: true
  - key: "r"
    description: "Checkout a remote branch as FETCH_HEAD"
    command: "git fetch {{index .PromptResponses 0}} {{index .PromptResponses 1}} && git checkout FETCH_HEAD"
    context: "remotes"
    prompts:
      - type: "input"
        title: "Remote:"
        initialValue: "{{index .SelectedRemote.Name }}"
      - type: "menuFromCommand"
        title: "Remote branch:"
        command: "git branch  -r --list {{index .PromptResponses 0}}/*"
        filter: ".*{{index .PromptResponses 0}}/(?P<branch>.*)"
        valueFormat: "{{ .branch }}"
        labelFormat: "{{ .branch | green }}"
  - key: "<f1>"
    command: "git reset --soft {{.CheckedOutBranch.UpstreamRemote}}"
    context: "files"
    prompts:
      - type: "confirm"
        title: "Confirm:"
        body: "Are you sure you want to reset HEAD to {{.CheckedOutBranch.UpstreamRemote}}?"
